# Адрес мастерноды с открытым доступом к API, по умолчанию - мастернода разработчиков NOAH
address = "https://api.noah.stakeholder.space" # todo
# Правила для аккаунтов по нодам, в которых - публичные ключи мастернод и процентное соотношение,
# суммарно 100, без знака % и только целое число
nodes = [ 
	["rule1", "Np7a888a7873121c4a5bfa9e1e0c07b5e6191ced294e63c6dd28d493981292f10d", "60"],
	["rule1", "Npf764cb0fd31cb88ffd23024c5d66969e107d53a4460a12821fb9d1ad66c39c9d", "30", "VALIDATOR"],
	["rule1", "", "10", "ROYALTY"]
]

# Приватные ключи аккаунтов с правилами делегирования
accounts = [ 
	["...", "rule1"],
	["...", "rule1"],
	["...", "rule1"] 
]
# Минимальная сумма делегирования для правил
min_amount = [
	["100", "rule1"]
]
# Время ожидания между делегированием (в минутах)
timeout = 10
# Тип сети main или test
chain = "main"
# Максимальный коэф. оплаты комиссии
max_gas = 2